apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    </head>
    <body>
    <h1>HI!<h1>
    </body>
    </html>
